### ISSUE TITLE
Permission to use dataset

### ISSUE THREAD

**Issue by aFku** [mnicolas94/BIVTatt-Dataset#1]
Hi. Is it required to get permission from you if I want to use your dataset in my master thesis, or it is free to use, and I only have to mention your paper with the statement from NOTES?

Best regards.

**Comment by mnicolas94** [comment]
Hi, it is free to use. We will apreciate if you mention our paper in your thesis.

**Comment by aFku** [comment]
Okey. Thank you for information.
